### ISSUE TITLE
warning: Update AD Schema for LAPS and add PShell add-on

### ISSUE THREAD

**Issue by davidm40** [HardenAD/SecureAD#104]
Bonjour,
Je reçois un warning lors de l'étape de du paramétrage de LAPS :
warning: Update AD Schema for LAPS and add PShell add-on

**Describe the bug**
2024/05/16 14:51:26	[INFO]	NEW TASK: Update Ad schema for LAPS and deploy PShell tools
2024/05/16 14:51:26	[DBUG]	--- ----: Calling function Install-Laps with parameters ForceDcIsSchemaOwner
2024/05/16 14:51:29	[DBUG]	--- ----: function's ended
2024/05/16 14:51:29	[DBUG]	--- ----: TaskID     = 134
2024/05/16 14:51:29	[DBUG]	--- ----: TaskName   = Update Ad schema for LAPS and deploy PShell tools
2024/05/16 14:51:29	[DBUG]	--- ----: TaskResult = warning
2024/05/16 14:51:29	[DBUG]	--- ----: Message    = LAPS installed but the schema extension has failed (warning: .Net 4.0 or greater requiered)

**OS**
 - Windows Server 2022
 - Dot Net 4.8.1 already installed

**Comment by bastienperez** [comment]
Je ne reproduis pas l'erreur avec la même configuration.

Le compte utilisé est bien membre `Schema Admins` (`Administrateurs du schéma` en FR) ?
A noter que si tu viens de t'ajouter dans le groupe, tu dois te déconnecter/reconnecter pour mettre à jour ton jeton.

En complément, peux-tu peux donner :
- ta version exacte WS Server 2022 (commande `winver`)
- ta version PowerShell (commande `$PSVersionTable`)
- version .NET (commande `Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -name Version,Release -ErrorAction SilentlyContinue | Where-Object { $_.PSChildName -match '^(?!S)\p{L}'} | Select-Object PSChildName, Version, Release`
- langue de ton OS

**Comment by davidm40** [comment]
J'utilise le compte Administrateur sur mon Lab pour le déploiement du script. La commande "Get-AdPrincipalGroupMembership Administrateur | Select name" me renvoie bien "Administrateurs de l'entreprise" ET "Administrateurs du schéma".
winver : Win Server 2022 21h2 v20348.2402)
$PsversionTable : 
![image](https://github.com/LoicVeirman/HardenAD/assets/47184862/5b59fea7-43eb-46c5-bb6e-e3c736fc7d92)
version .NET
![image](https://github.com/LoicVeirman/HardenAD/assets/47184862/5e2c4c47-306c-4d85-b071-a8bdecbba024)
langue OS : Français

**Comment by LoicVeirman** [comment]
Bonjour Davidm40,

Tu auras surement noté le petit paramètre *Calling function Install-Laps with parameters ForceDcIsSchemaOwner* : cette commande ne peut fonctionner que le sur DC avec le role FSMO Schema Master (une idée saugrenue je pense d'un de mes camarades mais bon... Sont jeunes :)). 

Etait-ce bien le cas ?

Sinon, il me faut le log de debug de la fonction.

**Comment by davidm40** [comment]
Bonjour,
je confirme exécuter les scripts sur le Schema Master, (netdom query fsmo renvoie bien le nom de ma machine).
Je ne vois rien de concluant dans le log (mais ce n'est peut-être pas celui attendu...)
[Debug_Set-LapsScripts.log](https://github.com/user-attachments/files/15511885/Debug_Set-LapsScripts.log)
[2024-05-16_025140_HardenAD-Results.log](https://github.com/user-attachments/files/15511891/2024-05-16_025140_HardenAD-Results.log)

Merci

**Comment by LoicVeirman** [comment]
La, c'est pas un pb de script mais un pb spécifique chez toi. A ta place, j'ouvrirai la fonction appelée (elle est dans le log) et je l'exécuterai ligne à ligne pour voir les retours d'erreurs. De plus, pour que l'extension de schéma fonctionne, il faut que 1/ le module LAPS soit en mémoire et 2/ que tu sois en mode administrateur dans pShell.
