### ISSUE TITLE
Automatic language selection

### ISSUE THREAD

**Issue by davidm40** [HardenAD/SecureAD#105]
Le paramétrage via le GUI est une très bonne idée. Il faudrait étendre cela en permettant de sélectionner la langue EN-US ou FR-
FR afin que le fichier TaskSequence_HardenAD.xml soit modifié en conséquence et commente/décommente les lignes en fonction pour 
"Builtin Groups", "Delegation for auditing computer creation and deletion","WellKnownID".

**Comment by LoicVeirman** [comment]
Bonne idée, on va mettre l'auteur de la GUI dessus.

**Comment by LoicVeirman** [comment]
Le script a été adapté pour remplir dynamiquement le nom des objets dans la table de traduction du fichier XML. Il n'est désormais plus nécessaire de configurer la langue.
