### ISSUE TITLE
GPO --> Error 4098, 8198

### ISSUE THREAD

**Issue by GRPDAN01** [HardenAD/SecureAD#113]
Hello,

I 'm facing an issue with the "HAD-LocalAdmins-XXXX" GPOs.

They all fail with two entry in the 'Application' event viewer.

Event 8198

`L’élément de préférence « Administrators (built-in) » ordinateur de l’objet de stratégie de groupe « HAD-LocalAdmins-T2 {60A1B9EA-4775-4E46-9C94-193C06462DC5} » n’a pas été supprimé car il a échoué avec le code d’erreur «  » Voir le fichier de suivi pour plus d’informations.`

Event 4098

`L’élément de préférence « Administrators (built-in) » ordinateur de l’objet de stratégie de groupe « HAD-LocalAdmins-T2 {60A1B9EA-4775-4E46-9C94-193C06462DC5} » n’a pas été appliqué car il a échoué avec le code d’erreur « 0x80070534 Le mappage entre les noms de compte et les ID de sécurité n’a pas été effectué. » Cette erreur a été supprimée.`

As you can see I'm using a french version of WIndows (Server and Client). If it can helps finding the problem.

I'm done a lot of search but couldn't find the solution.

Hope someone can help here.

Thanks in advance,

Sébastien

**Comment by GRPDAN01** [comment]
After more research I found the problem occurs because there's not SID associated with the member

![gpp](https://github.com/LoicVeirman/HardenAD/assets/93593395/7482daaf-5939-4d51-a80b-5b00febcee54)

If I replace it with a group from the AD, I get a SID and the GPO applies correctly.

Am I missing something ?

**Comment by qschweitzer** [comment]
Bonjour Sebastien,
Je n'ai pas le pourquoi du groupe Administrators Builtin qui n'a pas de SID mais c'est sans doute normal.
Vu la GPO, il n'y a pas d'intérêt à l'appliquer à ce groupe.

De mémoire le groupe Builtin correspond en fait au groupe admin local d'un serveur/PC. C'est à dire qu'il donne des privilèges uniquement sur les serveurs qui sont DC.

Je ne sais pas ce que fait cette GPO mais peut-être peux-tu nous en dire plus si la réponse n'est pas suffisante ?

Merci, bonne soirée/journée.

PS: attention les groupes locaux sont désactivés sur un DC by design. D'où l'existence du "Builtin" dans un AD qui les remplace.

**Comment by GRPDAN01** [comment]
Bonjour,

La GPO en question 'HAD-LocalAdmins-T2' fait partie du déploiement d'HardenAD. Elle permet d'ajouter un groupe spécifique à chaque ordinateur dans le groupe Administrators (built-in).

De ce que j'a compris :

Une tâche planifiée crée un groupe de sécurité pour chaque ordinateur du domaine sous la forme L-S_LocalAdmins_XXX ou XXX représente le nom de l'ordinateur.

Ensuite la GPO en question est sensée ajouter ce groupe à l'ordinateur. Pour cela la GPO utilise une variable %ComputerName% afin de lier le bon groupe au bon ordinateur.

Mon problème est que cette GPO fini avec une erreur. Par contre si je sélectionne le groupe via le bouton de recherche alors j'obtiens un SID et la GPO s'applique correctement. C'est pour cela que je pense que le problème est lié à une absence de SID mais sans en être convaincu.

J'espère pouvoir trouver une solution à ce problème.

Sébastien

**Comment by LoicVeirman** [comment]
Bonjour,

Ca va être compliqué de claquer un SID sur un objet de groupe qui n'existe pas (la variable %computername% étant remplacée par le système lors du compute). Par conséquent, non, le problème ne vient pas de là.

Il faut regarder les logs de la fonction (voir le code, je ne l'ai plus en tête) : attention, la version 2.9.8 dispose d'un fix qui doit être utilisée et les versions antérieures comportaient des bugs sur ce point.

**Comment by AlexandreMonchain** [comment]
Bonjour Loic,

Pour info, j'ai le même problème. J'ai utilisé la dernière version d'Harden AD (première application sur mon domaine), les taches planifiées se sont bien déclenchées et les groupes sont bien correctement ajoutés au groupe administrateurs local mais pour autant j'ai toujours des erreurs dans le journal d'évènement. 

![image](https://github.com/LoicVeirman/HardenAD/assets/14041278/b33eed9a-866b-4c79-9426-127e7328d998)
![image](https://github.com/LoicVeirman/HardenAD/assets/14041278/b4c352d3-f7aa-4fd4-a6d3-1060ef1f4261)
![image](https://github.com/LoicVeirman/HardenAD/assets/14041278/916d4ae3-7bc9-483d-a48d-90dba7ad0c63)

Merci d'avance

**Comment by AlexandreMonchain** [comment]
Update : 

![image](https://github.com/LoicVeirman/HardenAD/assets/14041278/7c06f1a8-0d82-4aa5-99cb-b5144f330699)

C'est pas un L-S_LocalAdmins mais L-S-LocalAdmins.

**Comment by GRPDAN01** [comment]
Bonjour,

Alors moi je m'étais rendu compte de cette coquille '-' à la place de '_'

Ce que j'ai fais c'est de renommer chaque groupe AD en remplaçant L-S-LocalAdmins par L-S_LocalAdmins afin que les noms de groupe correspondent aux GPO. J'ai également modifié le script de la tâche planifié afin qu'il crée les groupes en L-S_LocalAdmins

Du coup je pense que ma configuration est bonne (nom du groupe AD == nom du groupe GPO) mais cela ne fonctionne pas...

**Comment by LoicVeirman** [comment]
Wow. Coquille pourtant vérifiée 200 fois... Vous avez bien utilisez le ZIP et pas le code ?

<img width="907" alt="image" src="https://github.com/LoicVeirman/HardenAD/assets/85032445/3c06037f-db01-46bb-a88a-122261d12e40">

**Comment by LoicVeirman** [comment]
Dans le fichier de configuration des séquences de tâches, il y a un paramètre qui accueille le nom du groupe du cible : 

```<wellKnownID objectClass="group" translateFrom="%t0-localAdmin-servers%" translateTo="L-S-T0_LocalAdmins_Servers" />```

Je vais vérifier que le code de la tâche récupère bien cette information.

**Comment by LoicVeirman** [comment]
Il faut que je revoie le code, il y a un mismatch. Pour résoudre le problème, il faut modifier la GPO en mettant le bon nom de groupe OU corriger le fichier de configuration du script *set-LocalAdminGroups* (configuration.xml) en corrigeant ```<PREFIX-DOMLOC>L-S-</PREFIX-DOMLOC>```.

**Comment by GRPDAN01** [comment]
Bonjour Loic,

Pour ma part j'ai déjà fais la modification du préfix PREFIX-DOMLOC et aussi le renommage de tous les groupes via une commande Powershell.

![1](https://github.com/LoicVeirman/HardenAD/assets/93593395/629ce3ec-a0e2-457b-83a4-6ebd13ce277f)

![2](https://github.com/LoicVeirman/HardenAD/assets/93593395/9b53ea69-fd5e-4893-a991-83fa2ca8be20)

![3](https://github.com/LoicVeirman/HardenAD/assets/93593395/9efa634d-f62e-4d30-aafc-6405c5e44e3c)

Tout me semble bon de mon coté. Je suis sûr que c'est une bêtise à 2 balles mais je ne trouve pas pour le moment...

**Comment by LoicVeirman** [comment]
regarde dans l'OU *Administration / Tier X / LocalAdmins* : les noms des groupes correspondent-ils à celui de la GPO et le nom de la machine est-il correct ?

**Comment by GRPDAN01** [comment]
> regarde dans l'OU _Administration / Tier X / LocalAdmins_ : les noms des groupes correspondent-ils à celui de la GPO et le nom de la machine est-il correct ?

Oui les captures d'écran que j'ai publié au dessus sont des vues du Tier2 (AD et GPO)

**Comment by GRPDAN01** [comment]
Le nom des machines est correct également.

 On est d'accord que le nom des machines  n'inclus pas le signe dollar ($) que l'on retrouve souvent dans l'AD ?

**Comment by LoicVeirman** [comment]
non, pas besoin du dollars.

**Comment by LoicVeirman** [comment]
peux-tu m'envoyer ton fichier de configuration taskSequence.xml sur notre adresse de contact (en object: debug gpo pour loic) ?

**Comment by AlexandreMonchain** [comment]
@LoicVeirman je te confirme que je suis passé par le ZIP. Je vais modifier ces GPO manuellement, l'important c'est que ce soit corrigé pour les prochains qui passeraient par la :) 

@GRPDAN01 j'avais exactement le même problème que toi mais j'ai corrigé par la GPO et non en renommant les groupes et depuis plus de problème. Je ne sais pas si cela joue, ça ne devrait pas mais dans le doute.... 

Je vais te donner un conseil basique, mais assure toi bien que ta GPO c'est réappliquée sur tes serveurs… Je pense que Loic sera plus à même de t'aider que moi pour le reste.  

Bon courage.

**Comment by GRPDAN01** [comment]
@loewyn Ta solution m'a mis la puce à l'oreille. Du coup je suis allé vérifier les attributs d'un des groupes que j'ai renommé et j'ai trouvé le coupable !

![4](https://github.com/LoicVeirman/HardenAD/assets/93593395/d0c35987-42ed-49d6-9a66-1ac592cd9e82)

Le script que j'ai utilisé pour renommer les groupes avec un '_' n'a pas mis à jour le sAMAccountName. Forcément ça ne risquait pas de fonctionner.
Cela explique aussi pourquoi cela a marché pour toi en modifiant la GPO et non le groupe.

Après modif du sAMAccountName et un coup de gpupdate /force, le groupe est bien appliqué à l'ordinateur.

Merci à @LoicVeirman  et @loewyn pour votre temps. En espérant que cela puisse servir à d'autres

**Comment by AlexandreMonchain** [comment]
Content pour toi ! Une dernière remarque, tu as un script en tache planifié qui créé automatiquement les groupes locaux pour les nouveaux serveurs, ce script va continuer à les créer avec un "_" donc il faudra que tu le modifie également si tu ne veux pas avoir le problème de nouveau par la suite.

**Comment by GRPDAN01** [comment]
@loewyn  Ma tâche planifiée est déjà en adéquation avec le préfixe de mes groupes donc de ce coté là c'est tout bon :-)

**Comment by LoicVeirman** [comment]
Ah, encore un qui a oublier le sAMAccountName ;) JE te garantie que tu ne l'oublieras plus :)
