### ISSUE TITLE
Changements nom des OUs

### ISSUE THREAD

**Issue by freud44** [HardenAD/SecureAD#114]
Bonjour

J'ai peut-être raté une doc ou une info, mais est-il possible de renommer les OU si on souhaite les adapter à un environnement AD particulier ?
Je suppose qu'il faut modifier tout le fichier configuration xml ?
Quid des scripts qui modifient les objets AD & qui contiennent aussi des noms d'OU ? il faut aussi les modifier non?

Je crains que ca ne soit assez long & fastidieux donc si une solution rapide existe, je suis prenneur ;)

**Comment by LoicVeirman** [comment]
hello,

C'est tout le but du fichier XML... Dans la section "OrganizationalUnits", tu peux définir les Noms des OU comme tu le souhaites (c'est un squelette, tu peux même le modifier). Ensuite, il y a des références dans les autres sections (en particulier dans la section "translation") qu'il faudra aussi amender. 

Rien d'exceptionnel, je le fais souvent pour mes clients.

**Comment by LoicVeirman** [comment]
Bonjour,

Le fichier TasksSequence_HardenAD.xml est précisément là pour ca : vous y nommez les OU comme vous le souhaitez (section OrganizationalUnits). Ensuite, pensez à mettre à jour le nom de vos OU dans les différents points d’appel du fichier (distinguishedName, Translation, etc.).

Normalement, les scripts lisent le fichier XML pour trouver les informations !

Cdt,
Loic

De : freud44 ***@***.***>
Date : lundi, 17 juin 2024 à 18:00
À : LoicVeirman/HardenAD ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [LoicVeirman/HardenAD] Changements nom des OUs (Issue #114)

CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Bonjour

J'ai peut-être raté une doc ou une info, mais est-il possible de renommer les OU si on souhaite les adapter à un environnement AD particulier ?
Je suppose qu'il faut modifier tout le fichier configuration xml ?
Quid des scripts qui modifient les objets AD & qui contiennent aussi des noms d'OU ? il faut aussi les modifier non?

Je crains que ca ne soit assez long & fastidieux donc si une solution rapide existe, je suis prenneur ;)
