### ISSUE TITLE
TS never start automatically since first manually start

### ISSUE THREAD

**Issue by livarkhal** [HardenAD/SecureAD#115]
Hi :D 

A new issue found today on the tasksequences.
It seems they never start automatically. I need to start them manually 1 time after install and then they works automatically fine.

Thanks :)

**Comment by LoicVeirman** [comment]
Added to our bug pipe.

**Comment by LoicVeirman** [comment]
After a deep check, found that all tasks properly runs on schedule.

We are rewriting the Task Schedule scripts to reloclize them to %ProgramData%, hence we close this thread.
