### ISSUE TITLE
Format-XMLData error

### ISSUE THREAD

**Issue by jq-yeraz** [HardenAD/SecureAD#116]
When launching HardenAD.ps1 for the first time on a new DC with the latest release,  I got an error, it's doesn't find the Format-XMLData function. I added an import on the top of ps1 file to resolve it.

`Import-Module "$PSScriptRoot\Modules\Format-XML.psm1"`

**Comment by LoicVeirman** [comment]
Checked: the *format-xml* function is declared in hardenad.ps1.
