### ISSUE TITLE
[TS-LocalAdmins] Set-LocalAdmins.ps1 cannot work outside PDC

### ISSUE THREAD

**Issue by lmeot-syn** [HardenAD/SecureAD#120]
**Describe the bug**
All AD objects modification ran by the .ps1 script on standard DC cannot be achieved since the TS is ran under LOCALSYSTEM(DC Identity) and this Id does not have any modification right on PDC.

**To Reproduce**
1. Deploy the GPO on any DC but PDC
2. Make the TS run by triggering it (moving AD Computer for ex)
3. See event viewer for failed action

**Expected behavior**
This script must work on any DC. We cannot deploy it centrally since the event ID needed to run the task are generated locally on DC.

**Proposed Solution**
Change all call to variable $myPDC to localhost

**Comment by LoicVeirman** [comment]
Integrated to QuickFix August 2024 (on going)

**Comment by LoicVeirman** [comment]
Done.
