### ISSUE TITLE
Erreur dans la GPO HAD-LoginRestrictions-Paw

### ISSUE THREAD

**Issue by jmarc84Amu** [HardenAD/SecureAD#124]
Bonjour,

Lors du déploiement initial il y a une  erreur pour le gpo HAD-LoginRestrictions-Paw. Le domaine n'est pas modifié et reste en HARDEN\L-S-T0_PawAccess_Logon.

![harden-error-Paw](https://github.com/user-attachments/assets/257398a5-cf50-4a43-ac6f-5204261e79ed)

**Comment by LoicVeirman** [comment]
Bonjour,

La présence du SID indique pourtant que la réécriture c'est correctement passée. Pourriez me communiquer le log "debug_New-GpoObject.log" ?

**Comment by jmarc84Amu** [comment]
Voici le fichier.
[Debug_New-GpoObject.log](https://github.com/user-attachments/files/16548816/Debug_New-GpoObject.log)

**Comment by LoicVeirman** [comment]
Pas d'erreur. Peux-tu me retourner tous les logs dans un zip ?

**Comment by jmarc84Amu** [comment]
[Logs.zip](https://github.com/user-attachments/files/16549059/Logs.zip)

**Comment by LoicVeirman** [comment]
fan de K2000 et Alerte à malibu, hein ? :) Je regarde.

**Comment by LoicVeirman** [comment]
De ce que je vois dans les logs, le SID est bien celui de ton domaine.
Ton annuaire est également en français. 

Peux-tu m'envoyer les fichiers **HardenAD.migtable**, **Translated.migtable** et **translation.xml**, présents à la racine de : 
``./inputs/GroupPolicies/HAD-LoginRestrictions-Paw/{BB58C8C0-81A4-403E-99ED-E18F0C577632}``

Ainsi que le fichier **tasksSequences_hardenAD.xml**, dans le dossier ./configs ?

Merci à toi.

**Comment by LoicVeirman** [comment]
J'ai le même pb sur un AD en anglais.

**Comment by LoicVeirman** [comment]
Il y a une erreur dans le nom du groupe qui doit être traduit : 
<img width="2144" alt="image" src="https://github.com/user-attachments/assets/d27b9d2c-a37f-4944-9eb6-28b6d9857897">

Du coup, le nom n'est pas changé, mais le SID est correctement remplacé.

**Comment by LoicVeirman** [comment]
Branche 2.9.8 corrigée. Je pousse un QuickFix dans la journée.

**Comment by jmarc84Amu** [comment]
Top Merci. Après avec  le fix de Août 2024, cette release est presque parfaite pour un vrai déploiement. 
Oui je suis plus fan de k2000 et sharknado que d'alerte à Malibu

**Comment by LoicVeirman** [comment]
Attends de voir la 2.10 :)
