### ISSUE TITLE
HAD-WebProxyAutoDiscovery-Disabled and Windows 11 : all networks cards disabled

### ISSUE THREAD

**Issue by Math6768** [HardenAD/SecureAD#125]
**Describe the bug**
Activation on GPO HAD-WebProxyAutoDiscovery-Disabled causes issues on WIN11 system
Network cards are disabled and cannot be enabled

**To Reproduce**
- Activate GPO HAD-WebProxyAutoDiscovery-Disabled for a WIN11 computer
- Force GPO update
- After computer reboot, network cards are disabled

**Expected behavior**
In WIN11 WebProxyAutoDiscovery seems to hae dependance with network manager
Restrict GPO application by WMI filter can be a solution

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11

HardenAD 2.9.7

**Comment by LoicVeirman** [comment]
Hello,

Please, update the GPO from the 2.9.8 latest quickfix release.
