### ISSUE TITLE
GPO - Local Admin working partially on 2012 DC

### ISSUE THREAD

**Issue by lmeot-syn** [HardenAD/SecureAD#126]
**Describe the bug**
Scheduled task cannot be created on 2012 DC using the parameter in the GPO.

**To Reproduce**
1. Deploy HAD-TS-LocalAdmin on a 2012 DC
2. Check that the scheduled tasks are not created
3. Check the event log for GPO task scheduled error

**Expected behavior**
GPO Had-TS-LocalAdmins must work on any DC starting from 2008.

**Comment by LoicVeirman** [comment]
Hello,

2012 is not supported as system by MS, hence we won't spent time in making it working when the solution should be to upgrade your DC to at least to WS2016.

Give a try to release 2.10 (currently in its test stage), as the TS Scheduling process has been fully reviewed and no more rely on startup scripts.

**Comment by lmeot-syn** [comment]
Understood. Thank for your time.
