### ISSUE TITLE
HAD-Reset-KRBTGT-Password not imported 

### ISSUE THREAD

**Issue by Math6768** [HardenAD/SecureAD#132]
**Describe the bug**
HAD-Reset-KRBTGT-Password is not imported by installer
Manualy import does'nt work. GPO is not listed in GPO store.
Folder "C:\Windows\HardenAD\ScheduledTasks\HAD_Reset_KRBTGT_Password" is empty

**To Reproduce**
Install last version of HardenAD but HAD-Reset-KRBTGT-Password is not imported in GPO store

**Expected behavior**
There is a GPO which is named HAD-Reset-KRBTGT-Password which reset KRBTGT password every 30 days to prevent golden ticket atttack. 
Expect : GPO in GPO store 

**Screenshots**

**Desktop (please complete the following information):**
Win 2019

**Comment by LoicVeirman** [comment]
Hello Math6768,

Please share your logs (all of them). You can send this to me through the Harden Teams if you have an access.

Thank-you.

**Comment by LoicVeirman** [comment]
This GPO has been removed from the GPO bundle and should not be used. If you have a look to the GPO list, you'll find that this one is not part of the GP list imported.
