### ISSUE TITLE
Import New GPO Task - Warning - HardenAD-2.9.8_QF2024.08_BugFix124

### ISSUE THREAD

**Issue by dramces** [HardenAD/SecureAD#136]
**Describe the bug**
Avec la version HardenAD-2.9.8_QF2024.08_BugFix124, impossible de finir la tâche "Import New GPO or Update existing ones".
Warning with "Failed to create GPO groups : DENY"

**To Reproduce**
Lancement du script "HardenAD-2.9.8_QF2024.08_BugFix124" et warning sur la tâche précisée ci-dessus.
Les groupes liés aux GPO ne sont pas créés. Les GPO oui.
J'ai initialement cru à un problème de droit jusqu'à utiliser le built-in admin...
Au passage, les blocs français n'existent pas sur la bug fixe"

Je suis passé à la version 2.9.8 (zip github) et bon fonctionnement du script.

**Expected behavior**
Création des groupes liés aux GPO

**Screenshots**
Malheureusement plus de log car maquette refaite.

**Desktop (please complete the following information):**
 - OS: Windows 2016 server sous HyperV on promise. ADDS installé basiquement.
 - Version : HardenAD-2.9.8_QF2024.08_BugFix124

**Additional context**
Je débute en Github car travaille sur des SI coupés d'internet. Je débute également en durcissement d'AD mais faute de directive, je m'y lance via HardenAD. Merci à la communauté pour ce que vous faites.

**Comment by LoicVeirman** [comment]
bonjour @dramces,

Ce problème vient de ton environnement - je joues le script régulièrement et je peux te certifier qu'il n'y a pas de souci dans le code (il s'agit du même dans le zip et sur la branche *master*).

Pour plus de détails, il me faut les logs de l'installation (répertoire Logs) et les fichiers de configuration (répertoire config).

Concernant la partie en français, c'est normal : le script remplace dynamiquement les valeurs en interrogant l'annuaire, il n'y a plus besoin de modifier à la main.

**Comment by dramces** [comment]
Bonjour Loic,

Merci pour ce retour.
Je vais rejouer l'autre version dés que possible et te fournir les logs et fichiers.
Ce qui est étrange, c'est que d'une version à l'autre, le script fonctionne ou pas.
Je n'ai fait que re-claquer des points de contrôle et utiliser le même compte...

Mais étant débutant en durcissement d'AD (on a toujours compter sur le fait d’être déconnecter totalement d'Internet), l'erreur vient surement de moi. D'ailleurs, ce qui me manque une fois Harden lancé, c'est comment peupler tout ça ! J'ai encore du mal avec cette notion de tiering malgré les vidéos et lectures... Bref. Là n'est pas le sujet ;-)

Le temps pour moi de remonter le LAB...

Merci encore !

**Comment by LoicVeirman** [comment]
Je propose une offre d'accompagnement à l'année sur le produit (qui est normalement prévue pour ceux qui l'ont déjà déployé), rien n'interdit que je te l'étende à une formation sur le produit pour que vous soyez bien à l'aise ensuite en production.

Tu n'as qu'à me mettre un message en privé (ou me joindre sur Discord, je crois qu'on a déjà échangé sur IT Connect).

**Comment by dramces** [comment]
Loic,
Je viens de t'envoyer via Discord (ITConnect) un zip avec Logs et Confs.
J'ai également répondu à propos de ton offre :-)
A très vite !
Marc

**Comment by LoicVeirman** [comment]
Hello,

Après analyse : je te confirme que le problème vient de ton contexte de test (snap et ressource). Je clos le thread ici, mais on peut continuer la bavette sur ITCO.
