### ISSUE TITLE
HAD-DCLocaltor-Configuration not linked

### ISSUE THREAD

**Issue by davidm40** [HardenAD/SecureAD#139]
La GPO HAD-DCLocaltor-Configuration n'est pas liée dans le modèle. Elle devrait l'être au Container "Domain Controlrers".
+
Il y a une faute de frappe dans le groupe associé :
"L-S-GPO-Apply-HAD-DCLoctor-Configuration", semble-t-il a corriger par "L-S-GPO-Apply-HAD-DCLocaltor-Configuration"
![image](https://github.com/user-attachments/assets/3b1a98c4-63eb-49ef-a103-d73fbfcb6736)

**Comment by LoicVeirman** [comment]
Hi David,

This is expected. Using a dedicated DC for legacy is only required when the AD contains systems older than 2012. We have put this in place to limit the usage of old protocols on a DC (SMBv1, in our context). 

If, and only if, legacy systems are present then a setup should be made which include building a new DC, dedicate this one to the legacy and adapt the GPO to match the DC.

Regarding the name, it's a typo, I'll get this fixed.
