### ISSUE TITLE
GPO Login_Restrictions pour T0,T1 & T2 vides

### ISSUE THREAD

**Issue by freud44** [HardenAD/SecureAD#141]
**Describe the bug**
Bonjour,

Au lancement du script, aucune alerte ne se passe et je n'ai pas d'erreurs sur l'import des GPO, mais après vérification dans l'AD, je vois que les 3 GPOS Login_Restrictions_Tx sont vides

En analysant le log du répertoire debug, je trouve ceci : 

2024-11-28 08:02:39 ---> Creating GPO GPO_LoginRestrictions-T0
2024-11-28 08:02:39 ---> GPO GPO_LoginRestrictions-T0 has been created.
2024-11-28 08:02:39 ---> Trying to import datas of GPO GPO_LoginRestrictions-T0 :
2024-11-28 08:02:39 ---> Importing datas of GPO with translated.migtable
2024-11-28 08:02:40 ---! Failed to import Datas of GPO GPO_LoginRestrictions-T0
2024-11-28 08:02:40 ---! Error: The data is invalid. (Exception from HRESULT: 0x8007000D)
2024-11-28 08:02:41 ---> Deny permission has been applied on GPO GPO_LoginRestrictions-T0
2024-11-28 08:02:42 ---> Apply permission has been applied on GPO_LoginRestrictions-T0
2024-11-28 08:02:42 ---> Permission for authenticated users has been reset on GPO_LoginRestrictions-T0
2024-11-28 08:02:43 ---> GPO GPO_LoginRestrictions-T0 has been linked to OU OU=02-T0_Ressources,DC=secic01,DC=local

Une idée ?

Merci d'avance

**Comment by LoicVeirman** [comment]
Supprime les 3 GPO vides et relance le script. Parfois, l’import plante pour des problèmes de latence.
Si ce n’est pas le cas, il y a un souci avec le fichier translation.migtable et/ou translation.preftable.

Le 28/11/2024 17:12, « freud44 » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Describe the bug
Bonjour,

Au lancement du script, aucune alerte ne se passe et je n'ai pas d'erreurs sur l'import des GPO, mais après vérification dans l'AD, je vois que les 3 GPOS Login_Restrictions_Tx sont vides

En analysant le log du répertoire debug, je trouve ceci :

2024-11-28 08:02:39 ---> Creating GPO GPO_LoginRestrictions-T0
2024-11-28 08:02:39 ---> GPO GPO_LoginRestrictions-T0 has been created.
2024-11-28 08:02:39 ---> Trying to import datas of GPO GPO_LoginRestrictions-T0 :
2024-11-28 08:02:39 ---> Importing datas of GPO with translated.migtable
2024-11-28 08:02:40 ---! Failed to import Datas of GPO GPO_LoginRestrictions-T0
2024-11-28 08:02:40 ---! Error: The data is invalid. (Exception from HRESULT: 0x8007000D)
2024-11-28 08:02:41 ---> Deny permission has been applied on GPO GPO_LoginRestrictions-T0
2024-11-28 08:02:42 ---> Apply permission has been applied on GPO_LoginRestrictions-T0
2024-11-28 08:02:42 ---> Permission for authenticated users has been reset on GPO_LoginRestrictions-T0
2024-11-28 08:02:43 ---> GPO GPO_LoginRestrictions-T0 has been linked to OU OU=02-T0_Ressources,DC=secic01,DC=local

Une idée ?

Merci d'avance

**Comment by freud44** [comment]
Pour moi il manque des fichiers justement dans les répertoires des GPO, si on compare avec d'autres GPO bien appliquées.
Je n'ai pas forcément tous les fichiers dont tu me parle.
c'est peut être là le problème ?

**Comment by LoicVeirman** [comment]
Tu n’as pas dézippé à la racine (C:\HAD) ?

Le 29/11/2024 07:54, « freud44 » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Pour moi il manque des fichiers justement dans les répertoires des GPO, si on compare avec d'autres GPO bien appliquées.
Je n'ai pas forcément tous les fichiers dont tu me parle.
c'est peut être là le problème ?

**Comment by freud44** [comment]
J'ai mis cela dans un C:\temp\ pr éviter les problèmes de chemins trop longs.
Mais en fait j'ai autant de fichier que dans le master du git et/ou l'archive d'août qui a eu des fix d'appliqués.

C'est pas à la source qu'il en manquerait tout simplement?

**Comment by LoicVeirman** [comment]
Non, je l’ai encore déployé la semaine dernière en lab.

Vérifies les fichier de traduction.

Le 29/11/2024 09:20, « freud44 » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

J'ai mis cela dans un C:\temp\ pr éviter les problèmes de chemins trop longs.
Mais en fait j'ai autant de fichier que dans le master du git et/ou l'archive d'août qui a eu des fix d'appliqués.

C'est pas à la source qu'il en manquerait tout simplement?

**Comment by freud44** [comment]
Mais si tu veux la GPO se déploie bien, il n'y a juste pas de paramétrage à l'intérieur.
et je ne comprends pas car le fichier de traduction semble OK

Sur ton lab, tu as bien le contenu de cette GPO appliqué avec les bons groupes etc?

**Comment by LoicVeirman** [comment]
Oui. Et à chaque déploiement. Il y a forcément un loup. En général, ça vient d’un groupe manquant qui fait planter la traduction.

Le 29/11/2024 11:49, « freud44 » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Mais si tu veux la GPO se déploie bien, il n'y a juste pas de paramétrage à l'intérieur.
et je ne comprends pas car le fichier de traduction semble OK

Sur ton lab, tu as bien le contenu de cette GPO appliqué avec les bons groupes etc?

**Comment by freud44** [comment]
ah j'ai compris pourquoi.
en faisant à la main un import des settings de ma GPO, j'ai remarqué que la table de traduction ne trouve pas certains groupes, notamment les groupes liés aux legacy objects.

En fait la partie Legacy, je l'ai mis en commentaire dans le task sequence .xml & donc ni GPO ni groupes ne sont créés dans mon environnement, donc l'import ne peut pas bien se passer

EDIT : ta réponse confirme ce que j'ai découvert par moi même

**Comment by freud44** [comment]
EDIT 2 : si je ne veux pas des OU legacy & des objets, j'ai juste à ne pas activer la création de ces OU dans le bas du fichier tash_sequence ? Ou bien avoir mis en commentaire les lignes du fichier suffit ?

**Comment by freud44** [comment]
En gros, est ce que cette tâche : 

`<Id Number="053" Name="Set Legacy Organizational Unit">
			<CallingFunction>Set-TreeOU</CallingFunction>
			<UseParameters>HardenAD_PROD-LEGACY</UseParameters>
			<TaskEnabled>No</TaskEnabled>
			<TaskDescription>set `(Tier Legacy` organizational unit</TaskDescription>
		</Id>`
		
Si je laisse à No, est ce que le déploiement va tenter de créer les objets AD liés aux legacy ?

**Comment by LoicVeirman** [comment]
Il faut créer l’OU legacy : tu n’en as a pas besoin aujourd’hui, mais 2025 arrivent vite avec son lot d’obso 😊

Le 29/11/2024 12:05, « freud44 » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

En gros, est ce que cette tâche :
Set-TreeOU HardenAD_PROD-LEGACY No set `(Tier Legacy` organizational unit

Si je laisse à No, est ce que le déploiement va tenté de créer les objets AD liés aux legacy ?

**Comment by freud44** [comment]
C'est pas faux ;)
