### ISSUE TITLE
Prefix OU structure with HAD

### ISSUE THREAD

**Issue by jmthia** [HardenAD/SecureAD#142]
Hello Loïc,

**Is your feature request related to a problem? Please describe.**
The entry OU created by default are _Administration, Provisionning, Harden_Tx.  

**Describe the solution you'd like**
I suggest to prefix all first level entry OU with HAD-, just like the GPO's name. We will have HAD-Administration, HAD-Provisionning, HAD-Tx, just like the GPO's name. This will highlight all HardenAD contributions to the OU tree and also group them in ADUC, ADAC and even PoSh.

By the way, iI don't think that a translation should be proposed for this prefix. But who knows, someone might already use it.

Best regards,
Jean Marie

**Comment by LoicVeirman** [comment]
Hi Jean-Marie,

The base concept of the script is to let the end user choose its own OU name. The more flexible we are, the more easier implementing it will be.
From my own experience, none are using the default naming convention, even many have chosen to keep their existing design with minor adjustments.

Regarding the naming choices:
. Using “_Adminstration” put the OU name at the top of the root, which isolate it from the “production” OU;
. “Provisionning” is now relocated within the Tier1and2 OU;
. “HardenrTx” must be renamed.

All of this can be done through the configuration file, which is a mandatory step prior to execute it on production.

Thanks for your input !

Le 28/11/2024 20:24, « jmthia » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Hello Loïc,

Is your feature request related to a problem? Please describe.
The entry OU created by default are _Administration, Provisionning, Harden_Tx.

Describe the solution you'd like
I suggest to prefix all first level entry OU with HAD-, just like the GPO's name. We will have HAD-Administration, HAD-Provisionning, HAD-Tx, just like the GPO's name. This will highlight all HardenAD contributions to the OU tree and also group them in ADUC, ADAC and even PoSh.

By the way, iI don't think that a translation should be proposed for this prefix. But who knows, someone might already use it.

Best regards,
Jean Marie
