### ISSUE TITLE
OU Legacy & GPO appliquées

### ISSUE THREAD

**Issue by freud44** [HardenAD/SecureAD#143]
Bonjour

J'ai remarqué un comportement étrange, mais je pense "normal", mais qui vaudrait à une petite évolution à l'occasion.

Dans le déploiement d'Harden AD, au niveau du fichier de conf de la task sequence, on peut choisir de déployer ou non les OU Legacy.
Si on ne désire pas les déployer, le déploiement des GPOs se met en erreur car le link vers les OU Legacy ne peut se faire du fait qu'elles n'existent pas.

Est-ce qu'un test pourrait être rajouté quelque part afin de créer ou non des liens entre GPO & OU si on désire déployer les OU Legacy ou non ?

A défaut, je modifie le task sequence.xml mais bon, si on peut ajouter ce type de test, cela peut améliorer le déploiement :)

**Comment by LoicVeirman** [comment]
Les OU legacy DOIVENT être déployées, même si non utilisées actuellement, elles rempliront leurs rôles quand le parc aura à nouveau de l’obsolescence et permettent de ne pas surexposer les Tier.

Le 04/12/2024 09:59, « freud44 » ***@***.***> a écrit :


CAUTION: This email originated from outside your organization. Exercise caution when opening attachments or clicking links, especially from unknown senders.

Bonjour

J'ai remarqué un comportement étrange, mais je pense "normal", mais qui vaudrait à une petite évolution à l'occasion.

Dans le déploiement d'Harden AD, au niveau du fichier de conf de la task sequence, on peut choisir de déployer ou non les OU Legacy.
Si on ne désire pas les déployer, le déploiement des GPOs se met en erreur car le link vers les OU Legacy ne peut se faire du fait qu'elles n'existent pas.

Est-ce qu'un test pourrait être rajouté quelque part afin de créer ou non des liens entre GPO & OU si on désire déployer les OU Legacy ou non ?

A défaut, je modifie le task sequence.xml mais bon, si on peut ajouter ce type de test, cela peut améliorer le déploiement :)
