### ISSUE TITLE
XML hardcoded in some parts of code

### ISSUE THREAD

**Issue by k1dvh** [HardenAD/SecureAD#30]
In some code snippets, the path to the XML is hard-coded. Even if you call Harden AD with the "TasksSequence" parameter, it is not taken into account.

For example:
https://github.com/LoicVeirman/SecureAD/blob/4f53be26a28d914a8ee71cab51778914603a136c/Modules/object.psm1#L66

**Comment by LoicVeirman** [comment]
Code reviewed in 2.9.7.
