### ISSUE TITLE
$DomainDN never initialized, cannot work. $Searcher will always be null

### ISSUE THREAD

**Issue by k1dvh** [HardenAD/SecureAD#36]
https://github.com/LoicVeirman/SecureAD/blob/59e15e1ce85811e17a15501bb2a9d7e921319228/Modules/object.psm1#LL172C97-L172C97

**Comment by kdvhh** [comment]
Value can be found as $DomainRootDN : 
https://github.com/LoicVeirman/SecureAD/blob/59e15e1ce85811e17a15501bb2a9d7e921319228/Modules/object.psm1#LL103C10-L103C61

**Comment by LoicVeirman** [comment]
Fix is ok. Checked in 2.9.7.
