### ISSUE TITLE
Improvment for local administration creation

### ISSUE THREAD

**Issue by msreport** [HardenAD/SecureAD#41]
If the local IT team renames the parent OU after Harden AD deployment, a manual change is required.
The good way could be to use an attribute like admindescription to store the fact that the OU is an Harden root OU.

<?xml version="1.0" encoding="utf-16"?>
<Config>
    <Keys Name="Local Admin's OU for T0 members" Value="OU=LocalAdmins,OU=GroupsT0,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="Local Admin's OU for T1 members" Value="OU=LocalAdmins,OU=GroupsT1,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="Local Admin's OU for T2 members" Value="OU=LocalAdmins,OU=GroupsT2,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="Local Admin's OU for Legacies Workstations" Value="OU=LocalAdmins,OU=GroupsT2L,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="Local Admin's OU for Legacies servers" Value="OU=LocalAdmins,OU=GroupsT1L,OU=Administration,DC=had295,DC=intra"/>

    <Keys Name="Production OU for T0 members" Value="OU=Harden_T0,DC=had295,DC=intra"/>
    <Keys Name="Production OU for T1 members" Value="Ou=Servers,OU=Harden_T12,DC=had295,DC=intra"/>
    <Keys Name="Production OU for T2 members" Value="OU=Workstations,OU=Harden_T12,DC=had295,DC=intra"/>
    <Keys Name="Production OU for TLegacy members" Value="OU=Harden_TL,DC=had295,DC=intra"/>

    <Keys Name="PAW OU" Value="OU=PawAccess,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="PAW OU for T0" Value="OU=PawT0,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="PAW OU for T12L" Value="OU=PawT12L,OU=Administration,DC=had295,DC=intra"/>
    <Keys Name="Nomenclature for Local Admin groups" Value="L-S_LocalAdmins_%ComputerName%"/>
</Config>

**Comment by LoicVeirman** [comment]
The script is being rewritten and we have this into account. Closing.
