### ISSUE TITLE
Missing WMI filter for X32 and X64 computer for all computers and only for member servers

### ISSUE THREAD

**Issue by msreport** [HardenAD/SecureAD#42]
We need 4 additionnal WMI filters.
- X64
- X32
- X64 for members servers only
- X32 fr members servers only
The two last filters must be linked to the following GPO : 
  HAD_LAPS_X64_Deployment
  HAD_LAPS_X86_Deployment

**Comment by LoicVeirman** [comment]
Present in version 2.9.7. Found that there is duplicate entries in the WmiFilter section, cleaned-up in branch 2.9.7_BugFixes.
