### ISSUE TITLE
Windows_Server_Only wmi filter issue

### ISSUE THREAD

**Issue by mouhamadsalao** [HardenAD/SecureAD#53]
Windows_Server_Only wmi filter : `select ProductType from Win32_OperatingSystem where ProductType = "2"` doesnt return any result when executed with following powershell query on Windows Server 2022 Domain Controller French Edition 
`qwmi -Query 'select ProductType from Win32_OperatingSystem where ProductType = "2"'`
![image](https://github.com/LoicVeirman/SecureAD/assets/139865972/7f051f76-a6a8-467a-8b1c-eccf6b3460ea)

Which cause issues on applying some GPO with this filter

**Comment by mouhamadsalao** [comment]
After a gpresult
![image](https://github.com/LoicVeirman/SecureAD/assets/139865972/cff02005-9f11-40ac-acb8-bd7555dc0c1a)

**Comment by mouhamadsalao** [comment]
This filter can do the job 
`select ProductType from Win32_OperatingSystem WHERE Caption LIKE "%server%"`

**Comment by LoicVeirman** [comment]
Hi @mouhamadsalao : I just review this and the WMI filter is functional.
<img width="793" alt="image" src="https://github.com/LoicVeirman/SecureAD/assets/85032445/167ae6a5-a9aa-4d39-b699-e76a80b7f83d">

We do not use the filter based on the caption, as the productType allow us to dissociate DC from member servers.
