### ISSUE TITLE
Keepass File \Outputs\HardenAD.kdbx not found

### ISSUE THREAD

**Issue by bro566** [HardenAD/SecureAD#63]
Bonjour Loic,

Sur le script de séquence de tache, il est indiqué qu'un fichier HardenAD.kdbx est crée dans le répertoire ( \Secure-AD\Outputs\). Or je n'ai qu'un fichier AccountsPassword.txt qui s'est crée à cette emplacement. Est ce qu'il ya autre chose à faire que je n'ai pas vu dans les commentaire du script TasksSequence ?

**Comment by LoicVeirman** [comment]
Si le fichier n'est pas créé avec succès, les comptes sont inscrits dans le fichier TXT en fallback. Il faut aller lire le log "New-AdministrationAccounts.log" pour voir ce qu'il s'est passé.
