### ISSUE TITLE
Start-HardenADLocalGroups : config.xml issue

### ISSUE THREAD

**Issue by LoicVeirman** [HardenAD/SecureAD#64]
The file Config.xml (Private/config) contains bad data.
The file should be adapted with client value to identify the target OU hosting groups and machines.

Pb : the xml file contains no %...% value.

Acting : replace the value to include dynamic data coming from the <translation> section.

Example :
**Current value:**    
`<Keys Name="Local Admin's OU for T0 members" value="OU=LocalAdmins,OU=GroupsT0,OU=_Administration,DC=harden,DC=lab">`

**New value:**
`<Keys Name="Local Admin's OU for T0 members" Value="OU=%LocalAdm%,OU=%T0-Groups%,OU=%AdminOU%,%rootDN%=>`

**Comment by kdvhh** [comment]
Hi Loic,

In the GroupPolicy module, when you translate the preferences table, you retrieve the contents of the backup file.
Now, if you look at my config.backup file and the translation.xml file, you'll see that it matches. So, in my opinion, there's no problem.

**Comment by kdvhh** [comment]
If we want to improve code quality, there should be no .backup before the first launch of the Harden AD tool. We should therefore retrieve the .backup values and overwrite them in the original file before deleting the .backup.

**Comment by LoicVeirman** [comment]
Hi K1dvh,

It doesn't work. Even worse, once fixed I found that the file is replaced on the DC and I even don't know why (script was not reran). We need to investigate deeper this code: the way it is implemented is too complex for troubleshooting. Let me know when we can work together on this - the script works pretty well, we only need to ensure its deployment is as easy as possible.

**Comment by LoicVeirman** [comment]
File modified and copied on all DC on the 20th (also modified on the HAD local repo):
<img width="1806" alt="image" src="https://github.com/LoicVeirman/SecureAD/assets/85032445/362807fa-591b-465d-a496-44bb653e6381">

This has worked nicely up to Saturday 24th: groups where created/moved/flushed nicely.

Then, a new server has been add on Tuesday 26th: the localAdmin group was not created. The file were replaced, as shown below:
<img width="1584" alt="image" src="https://github.com/LoicVeirman/SecureAD/assets/85032445/35bd5b30-96fe-4b98-98b4-4eee80a6e4c1">


So, it means somehow a process is in place and replace the file on its own...

**Comment by LoicVeirman** [comment]
Another bug: if the script failed the first time, it does not create group on move.

<img width="1190" alt="image" src="https://github.com/LoicVeirman/SecureAD/assets/85032445/8f21bb75-6918-4662-af90-4e5404b45b0f">

We need to ensure that the script check if the group is present, create it if missing, then place it to the right OU.

**Comment by LoicVeirman** [comment]
Another minor issue, but quite perturbing : a new computer added to the provisioning OU is randomly tiered... exemple:
<img width="1579" alt="image" src="https://github.com/LoicVeirman/SecureAD/assets/85032445/f27c037d-2eb0-4f61-bea2-2754ae84a249">

**Comment by LoicVeirman** [comment]
Fixed.
