### ISSUE TITLE
Domain controllers -> T0 ?

### ISSUE THREAD

**Issue by Joffrey54** [HardenAD/SecureAD#66]
Hi,

I don't understand why there are some GPO (ex: HAD-Reset-KRBTGT-Password) linked to "Domain Controllers" OU: your documentation explains that Domain Controllers can be in the T0 OU.
![image](https://github.com/LoicVeirman/SecureAD/assets/3739340/9d3054cc-02c9-4ba3-8e7b-acc222ab2b78)

Thanks you !

**Comment by bastienperez** [comment]
I'm not the documentation writer, but I think this is more of a "problem" with the sentence in the documentation.
The domain controllers stay in the domain controller OU, even if they are Tier0

**Comment by LoicVeirman** [comment]
French speaker are not english natural born writers... It is obvious that DC remains in DC OU, there are specifics GPO to them (default domain controller policy as an example) and specific security consideration too. You can move away the DC, AD still works but you may experience severe security issues and some non-running software.
