### ISSUE TITLE
GPO Groups T0 T12 Location

### ISSUE THREAD

**Issue by paracetamol32** [HardenAD/SecureAD#67]
Hello, is it normal that all groups related to the application of GPO Tier 1, 2 are created within the OU _Administration/GroupsT0/GPO ?

![image](https://github.com/LoicVeirman/SecureAD/assets/14573835/6177c1ce-11f6-4e0a-8870-2f8dd91f1b57)

**Comment by Joffrey54** [comment]
Hi, perhaps because only T0 admin can apply or update GPO.

**Comment by LoicVeirman** [comment]
Yes, it is. At the whole start of the story, we though that some GPOs may be handle by T2 or T1 guys. However, our own experience shows that is an unsafe approach as without appropriate software, you will need a Tier 0 account to handles GPO. Then, the ability to manage corresponding groups (apply/deny) remains to the Tier 0 guys too... But you can add a nested groups to let then T1/T2 guys applying them or not ; just keep in minds that should never be a security related one.
