### ISSUE TITLE
No Action  when running HardenAD.PS1

### ISSUE THREAD

**Issue by ssaad82** [HardenAD/SecureAD#68]
i get the following result whenever i run the script on my Lab AD:

pending: Upgrade DomainFunctionalLevel [?25lignored[0m[?25h
pending: Upgrade ForestFunctionalLevel [?25lignored[0m[?25h
pending: set msDSMachineAccountQuota to 0 to restrict domain junction[?25lignored[0m[?25h
pending: activate the AD Recycle Bin optional feature[?25lignored[0m[?25h
pending: set notify on every Site Links[?25lignored[0m[?25h
pending: set GPO Central Store and update adm and admx files[?25lignored[0m[?25h
pending: set Administration organizational unit[?25lignored[0m[?25h
pending: set Tier 0 organizational unit[?25lignored[0m[?25h
pending: set Tier 1 and Tier 2 combo organizational unit[?25lignored[0m[?25h
pending: set Tier Legacy organizational unit[?25lignored[0m[?25h
pending: set Provisioning organizational unit[?25lignored[0m[?25h
pending: set user objects default location[?25lignored[0m[?25h
pending: set computer objects default location[?25lignored[0m[?25h
pending: create administration accounts used by the tier model[?25lignored[0m[?25h
pending: create administration groups used by the tier model[?25lignored[0m[?25h
pending: Enforce Delegation ACEs used by the tier model[?25lignored[0m[?25h
pending: Import WMI filter to the domain[?25lignored[0m[?25h
pending: Import or update group policy objects to the domain and link them[?25lR[?25lu[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lU[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25lN[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25lN[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25lI[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25lN[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25ln[?25lG[?25lR[?25lu[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lU[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25lN[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25lN[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25lI[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25lN[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25ln[?25lG[?25lR[?25lu[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lU[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25lN[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25lN[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25lI[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25lN[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25ln[?25lG[?25lR[?25lu[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lU[?25ln[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25lN[?25ln[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25lN[?25li[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25lI[?25ln[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25lN[?25lg[?25lr[?25lu[?25ln[?25ln[?25li[?25ln[?25lG[?25lsuccess[0m[?25h
pending: Update AD Schema for LAPS and add PShell add-on[?25lignored[0m[?25h
pending: Set-up LAPS permissions on the target domain[?25lignored[0m[?25h
pending: Update LAPS Scripts to match with the domain name[?25lignored[0m[?25h
-------------------------
Exporting results to .\Logs\2024-01-26_101428_HardenAD-Results.csv...success
Exporting logging to .\Logs\2024-01-26_101428_HardenAD-Results.log...success

TaskID TaskResult TaskName                                         
------ ---------- --------                                         
005    ignored    Upgrade Domain Functional Level                  
006    ignored    Upgrade Forest Functional Level                  
010    ignored    Restrict computer junction to the domain         
020    ignored    Activate Active Directory Recycle Bin            
030    ignored    Set Notify on every Site Links                   
040    ignored    Set GPO Central Store                            
050    ignored    Set Administration Organizational Unit           
051    ignored    Set Tier 0 Organizational Unit                   
052    ignored    Set Tier 1 and Tier 2 Organizational Unit        
053    ignored    Set Legacy Organizational Unit                   
060    ignored    Set Provisioning Organizational Unit             
070    ignored    Default user location on creation                
071    ignored    Default computer location on creation            
080    ignored    Create administration accounts                   
090    ignored    Create administration groups                     
095    ignored    Enforce delegation model through ACEs            
125    ignored    Import additional WMI Filters                    
130    success    Import new GPO or update existing ones           
134    ignored    Update Ad schema for LAPS and deploy PShell tools
135    ignored    Setup LAPS permissions over the domain           
136    ignored    Update LAPS deployment scripts

**Comment by dxpestillalive** [comment]
+1

**Comment by Joffrey54** [comment]
have you enabled sections you want in the xml config file ?

**Comment by dxpestillalive** [comment]
Are you talking about configuration_hardenad.xml ?

**Comment by Joffrey54** [comment]
In TasksSequence_HardenAD.xml, in "Sequence" xml section:

![image](https://github.com/LoicVeirman/SecureAD/assets/3739340/9b029410-73d2-42b8-99e1-51a4e203d820)

You must configure each sequence ID

**Comment by dxpestillalive** [comment]
You solved it ! Thanks a lot

**Comment by ssaad82** [comment]
Thank you @Joffrey54!

**Comment by LoicVeirman** [comment]
Added to KB. Always read files before running www scripts...
