### ISSUE TITLE
An error occurred while generating report: Index and length must refer to a location within the string. Parameter name: length

### ISSUE THREAD

**Issue by kaismbarki** [HardenAD/SecureAD#70]
Hi,
multiple GPO displays error message when you want see config 

**An error occurred while generating report: Index and length must refer to a location within the string. Parameter name: length**

Attachement print screen
![18-02-2024 10-29-08](https://github.com/LoicVeirman/SecureAD/assets/62308930/2a798e79-2ba0-47a0-880b-8dd985ccecd1)

**Comment by LoicVeirman** [comment]
You shall have ran the script the bad way - please give us details, this part used to works with no issue.

**Comment by LoicVeirman** [comment]
in version 2.9.7, all GPOs were successfully added.
