### ISSUE TITLE
Scheduled Task : MCS - Sensitive Groups Flushing not functionnal

### ISSUE THREAD

**Issue by Math6768** [HardenAD/SecureAD#71]
Scheduled Task is created but location is incorrect.

Task is configure to start in %Windir%\HardenAD\TasksSchedulesScripts\MCS-GroupsFlushing but this directory doesn't exist (or is not created)
Result : 0x8007010B : not a valid directory 

![image](https://github.com/LoicVeirman/SecureAD/assets/159037932/1c24c696-915c-4b03-b1d3-027b2eb86b80)

**Comment by LoicVeirman** [comment]
A new release is being developped. The current one will be fixed soon.

**Comment by LoicVeirman** [comment]
The script is functional in version 2.9.7. However, I will remove the group list from the config.xml file to avoid disruption with permission given to Operator accounts.
