### ISSUE TITLE
Task sequence 160 Enable=No but seems executed

### ISSUE THREAD

**Issue by Math6768** [HardenAD/SecureAD#82]
Configuration : 

		<Id Number="160" Name="Cross integration of Admin groups">
			<CallingFunction>Add-GroupsOverDomain</CallingFunction>
			<UseParameters>
			</UseParameters>
			<TaskEnabled>No</TaskEnabled>
			<TaskDescription>Cross integration of `(administration groups` used by the tier model</TaskDescription>
		</Id>

But after script execution : 

![image](https://github.com/LoicVeirman/HardenAD/assets/159037932/4d6c4d3e-727a-48b6-8f19-3de5e393a471)

Expected : ignored 

HardenAD 2.9.7

**Comment by LoicVeirman** [comment]
That's expected. This is not a bug: the code has it was written is not able to handle a proper exit code. It always return success except if an issue is met.
