### ISSUE TITLE
Unable to deploy Harden AD in stable version 2.9.7

### ISSUE THREAD

**Issue by Aynqua** [HardenAD/SecureAD#86]
**Describe the bug**
Hello, 
Deployment of Harden AD in Stable 2.9.7 is impossible because the different tasks are ignored. (But in beta version 2.9.6 it works fine! On the same king of lab).

**To Reproduce**
1. Install a fresh lab Windows 2022 server with ADDS and setup the windows server as DC.
2. `DCDIAG` /V /E -->
3. `NETDOM` QUERY FSMO
4. Run Powershell as "Administrator" who is Enterprise Admins and Schema Admins.
5. cd C:\Users\Administrateur\Downloads\HardenAD-HardenAD-2.9.7
6. `.\HardenAD.ps1`

**Expected behavior**

**OUTPUT of .\HardenAD.ps1 :** 

Script Name: HardenAD Community Edition
Release Nbr: 02.09.007
Written by : HardenAD Community - contact@hardenad.net

Description: improve the security of your directory in minutes!
ignored: Upgrade DomainFunctionalLevel
ignored: Upgrade ForestFunctionalLevel
ignored: set msDSMachineAccountQuota to 0 to restrict domain junction
ignored: activate the AD Recycle Bin optional feature
ignored: set notify on every Site Links
ignored: set GPO Central Store and update adm and admx files
ignored: set Administration organizational unit
ignored: set Tier 0 organizational unit
ignored: set Tier 1 and Tier 2 combo organizational unit
ignored: set Tier Legacy organizational unit
ignored: set Provisioning organizational unit
ignored: set user objects default location
ignored: set computer objects default location
ignored: create administration accounts used by the tier model
ignored: create administration groups used by the tier model
ignored: Enforce Delegation ACEs used by the tier model
ignored: Import WMI filter to the domain
ignored: Import or update group policy objects to the domain and link them
ignored: Update AD Schema for LAPS and add PShell add-on
ignored: Set-up LAPS permissions on the target domain
ignored: Update LAPS Scripts to match with the domain name
success: Cross integration of administration groups used by the tier model

Exporting results to .\Logs\2024-04-03_104558_HardenAD-Results.csv...success
Exporting logging to .\Logs\2024-04-03_104558_HardenAD-Results.log...success

TaskID TaskResult TaskName

005    ignored    Upgrade Domain Functional Level
006    ignored    Upgrade Forest Functional Level
010    ignored    Restrict computer junction to the domain
020    ignored    Activate Active Directory Recycle Bin
030    ignored    Set Notify on every Site Links
040    ignored    Set GPO Central Store
050    ignored    Set Administration Organizational Unit
051    ignored    Set Tier 0 Organizational Unit
052    ignored    Set Tier 1 and Tier 2 Organizational Unit
053    ignored    Set Legacy Organizational Unit
060    ignored    Set Provisioning Organizational Unit
070    ignored    Default user location on creation
071    ignored    Default computer location on creation
080    ignored    Create administration accounts
090    ignored    Create administration groups
095    ignored    Enforce delegation model through ACEs
125    ignored    Import additional WMI Filters
130    ignored    Import new GPO or update existing ones
134    ignored    Update Ad schema for LAPS and deploy PShell tools
135    ignored    Setup LAPS permissions over the domain
136    ignored    Update LAPS deployment scripts
160    success    Cross integration of Admin groups

In the .\Logs\2024-04-03_104558_HardenAD-Results.log file, all skipped tasks have no "message".

Thanks in advance,
Best Regards,
Nathan.

**Comment by lewill03** [comment]
Hello,
At the end of the "TasksSequence_HardenAD.xml" file under Configs folder, you have to replace `<TaskEnabled>No</TaskEnabled>` by `<TaskEnabled>Yes</TaskEnabled>` in every task you want to execute!
Hope this helps.
