### ISSUE TITLE
Can't join computer to domain with Tier 2 Operator account

### ISSUE THREAD

**Issue by PSIT-smiro** [HardenAD/SecureAD#87]
**Bug description**
A T2 operator user can't join a computer to domain due to "Exceeded the Maximum Number of Computer Accounts Allowed to Create in this Domain" error. This expected behaviour is related to ms-DS-MachineAccountQuota set to 0 as we do not want standard users to join computers to domain. But, delegated permissions for T2 users should bypass this, right ?.

- Provisioning OU for computers is set to OU=Computers,OU=Provisioning,DC=intra,DC=domaine,DC=fr (this is the default configuration for Harden AD)
- Built-in user T2O-AHARDEN is member of group G-S-T2-Operators
- G-S-T2_Operators is member of group "L-S-T2-DELEG_Computer - Join Domain" group
- Delegations on "OU=Computers,OU=Provisioning,DC=intra,DC=domaine,DC=fr" seem to be correct : 
![image](https://github.com/LoicVeirman/HardenAD/assets/94846599/98f4270e-1ab8-464c-9914-9b3f743d6104)

**harden AD version 2.9.7**

**Comment by PSIT-smiro** [comment]
For troubleshooting purposes, I added the following delegated permissions to "L-S-T2-DELEG_Computer - Join Domain" on computer objects in "OU=Computers,OU=Provisioning,DC=intra,DC=domaine,DC=fr " :

- Create selected objects in the folder and Delete selected objects in this folder. 
- Reset password
- Read and write account restrictions
- Read and write DNS host name attributes
- Validated write to DNS host name
- Validated write to service principal name
- Write servicePrincipalName

Now, a T2 operator is able to join a computer to domain. Maybe the DelegationACEs in TaskSequence file should be modified to reflect these permissions ?

**Comment by LoicVeirman** [comment]
Hello,

It is expected that a T2 Ope or T1 Ope could not join a computer to the domain IF the object was not previously created in AD. 

The process should be: 
1. Create the computer object in the correct OU - this also bring all GPOs on domain joining.
2. Join the computer to the domain with the Operator account.

If you do not follow this process, an attacker can then stole an operator account (remember: this is the account that interact on the client's system) and will have ability to join it's own compromised computer to your domain. Such a bad idea....
