### ISSUE TITLE
Error during script execution

### ISSUE THREAD

**Issue by MaximePadre** [HardenAD/SecureAD#89]
Hello, 

When I run the Hardenad.ps1 script (version 2.9.7) on a blank Active directory in a lab, the various tasks return “Error” (see screenshot).
<img width="781" alt="image" src="https://github.com/LoicVeirman/HardenAD/assets/108010664/b1c690b3-e430-4e1d-aa6b-df88607ae70c">

As indicated in the documentation, I have carried out the backup and run the dcdiag /v /e and “NETDOM QUERY FSMO” commands.

I've also replaced the corresponding fields with the domain name/NetBIOS with mine.

The user I'm running the script with is in the “Enterprise Admins and Schema Admins” groups.

**Comment by Math6768** [comment]
Hi, 

You will find details of errors in debug file of each task : hardenpath\Logs\Debug
Maybe there is more explanations ?

**Comment by LoicVeirman** [comment]
That is not a script issue. Please ensure you have unblocked files and that the script is ran in the administrator mode.
