### ISSUE TITLE
tout est disable

### ISSUE THREAD

**Issue by jerome-taristas** [HardenAD/SecureAD#90]
Bonjour,
Aucune tâche ne se lance. Une idée s'il vous plait ?
Cordialement
[Uploading 2024-04-16_041601_HardenAD-Results.log…]()

**Comment by jerome-taristas** [comment]
2024/04/16 04:16:01	[INFO]	NEW TASK: Upgrade Domain Functional Level
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-ADFunctionalLevel with parameters Domain Last
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 005
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Upgrade Domain Functional Level
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Upgrade Forest Functional Level
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-ADFunctionalLevel with parameters Forest Last
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 006
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Upgrade Forest Functional Level
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Restrict computer junction to the domain
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-msDSMachineAccountQuota with parameters 0
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 010
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Restrict computer junction to the domain
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Activate Active Directory Recycle Bin
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-ADRecycleBin with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 020
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Activate Active Directory Recycle Bin
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set Notify on every Site Links
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-SiteLinkNotify with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 030
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set Notify on every Site Links
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set GPO Central Store
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-GpoCentralStore with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 040
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set GPO Central Store
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set Administration Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-TreeOU with parameters HardenAD_ADMIN
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 050
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set Administration Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set Tier 0 Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-TreeOU with parameters HardenAD_PROD-T0
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 051
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set Tier 0 Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set Tier 1 and Tier 2 Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-TreeOU with parameters HardenAD_PROD-T1and2
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 052
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set Tier 1 and Tier 2 Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set Legacy Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-TreeOU with parameters HardenAD_PROD-LEGACY
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 053
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set Legacy Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Set Provisioning Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-TreeOU with parameters PROVISIONNING-EN
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 060
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Set Provisioning Organizational Unit
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Default user location on creation
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-DefaultObjectLocation with parameters User OU=users,OU=provisioning,RootDN
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 070
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Default user location on creation
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Default computer location on creation
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-DefaultObjectLocation with parameters Computer OU=computers,OU=provisioning,RootDN
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 071
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Default computer location on creation
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Create administration accounts
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function New-AdministrationAccounts with parameters H4rd3n@D!!
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 080
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Create administration accounts
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Create administration groups
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function New-AdministrationGroups with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 090
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Create administration groups
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Enforce delegation model through ACEs
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Push-DelegationModel with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 095
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Enforce delegation model through ACEs
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Import additional WMI Filters
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Import-WmiFilters with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 125
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Import additional WMI Filters
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Import new GPO or update existing ones
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function New-GpoObject with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 130
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Import new GPO or update existing ones
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Update Ad schema for LAPS and deploy PShell tools
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Install-Laps with parameters ForceDcIsSchemaOwner
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 134
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Update Ad schema for LAPS and deploy PShell tools
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Setup LAPS permissions over the domain
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-LapsPermissions with parameters CUSTOM
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 135
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Setup LAPS permissions over the domain
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Update LAPS deployment scripts
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Set-LapsScripts with parameters NETLOGON\LAPS
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 136
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Update LAPS deployment scripts
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = disable
2024/04/16 04:16:01	[DBUG]	--- ----: Message    = 
2024/04/16 04:16:01	[INFO]	NEW TASK: Cross integration of Admin groups
2024/04/16 04:16:01	[DBUG]	--- ----: Calling function Add-GroupsOverDomain with parameters 
2024/04/16 04:16:01	[DBUG]	--- ----: function's ended
2024/04/16 04:16:01	[DBUG]	--- ----: TaskID     = 160
2024/04/16 04:16:01	[DBUG]	--- ----: TaskName   = Cross integration of Admin groups
2024/04/16 04:16:01	[DBUG]	--- ----: TaskResult = success
2024/04/16 04:16:01	[DBUG]	--- ----: Message    =

**Comment by livarkhal** [comment]
Bonjour,
Dans ton fichier TasksSequence_HardenAD.xml qui se trouve dans le dossier config, tu as bien enable toutes les tâches présentes dans la dernière partie du fichier <Sequence>?
Tu as les fonction <TaskEnabled>No</TaskEnabled> pour chaque module il faut les mettre sur yes :)

**Comment by jerome-taristas** [comment]
Aussi simple que ca :)
Merci beaucoup !!! Lab en place
Puis je abuser ? Je n'ai pas bien compris dans le webinaire de be cyber la différence entre le both et le apply pour les GPO.
Serait il possible d'avoir une vulgarisation du principe ?

**Comment by livarkhal** [comment]
Dans le fichier TaskSequence_HardenAD.xml à la ligne 406 tu as l'explication : 
---
Apply create a group that limit the application scope, whereas DENY enforce the application to everyone except the denied one. BOTH mix the two modes, enforcing application to only a scoped target group with an exception scope (usefull for migration or testing purpose). If mode is ommited, the mode BOTH will be used.
---

De ce que j'en ai compris, c'est qu'avec l'APPLY uniquement tu n'as pas le DENY, et vice versa (avec le DENY, ils laissent le paramétrage par défaut de la GPO).
Avec le BOTH, tu auras pour chaque GPO un groupe APPLY et un groupe DENY, mais pas de paramétrage par défaut. Donc tu devras remplir les groupes associés à tes GPO en APPLY pour appliquer la GPO à ton objet, même s'il est dans l'OU où la GPO est appliquée :)

**Comment by jerome-taristas** [comment]
Quelle rapidité ! Comme indiqué dans le webinaire il faut bien prendre le temps de regarder les commentaires du fichier.
Merci beaucoup !
