### ISSUE TITLE
T1 and T2 Managers / Administrators Active Directory Access

### ISSUE THREAD

**Issue by livarkhal** [HardenAD/SecureAD#91]
Hi :)

When we create an administrator or manager T1 or T2, there is no way for them to connect to active directory. So they can't access the Users and Computers Active Directory MMC. In the documentation and in the delegation groups, we see these accounts have to modify or create AD object. But we don't understand how they can connect on the Users and Computers Active Directory MMC to do it.

We are going to make some configuration out of the Harden AD to create these access, but we wanr to post here to see if we don't loose something in the configuration :D 

Thanks ;)

**Comment by Math6768** [comment]
What would you want to do  ?

For example L-S-T2-DELEG_Computer - Create and Delete is used to manage computer which already are in domain (in T2)
L-S-T2-DELEG_Computer - Join Domain is used to permit a user to add a computer to the domain (T2)
etc etc...
Delegation group names are quite clear. Just put a user in the correct delegation group. It works like a charm in my environment. 

To manage it from our computer just use RSAT, dsa.msc / run as / and use credentials from a users who hs been place in correct access group.

**Comment by livarkhal** [comment]
Hi, 

yeah but for the user creation for exemple, the manager T1 need to connect to Activ Directory Users and Computers no?
But they can't connect one the AD server via RDP, because they are only users ...

I think i have another problem on my PAW server, independant of harden AD ... We uses Harden Kitty to harden the OS server, and i think it's this who block elevation privilege for RSAT 😇

**Comment by Math6768** [comment]
You've right you cannot connect with RDP to T0 server with a T1 account. It's the goal of tiering :)
99% of management of AD objects is made by RSAT on our side. We almost never connect through rdp to the domain controller

**Comment by livarkhal** [comment]
Yeah you are right, i'm sorry to open this issue for nothing ...
Thanks for your confirmations :D
