### ISSUE TITLE
WMI Filter : Windows-x64-NoDC.mof

### ISSUE THREAD

**Issue by gherubel** [HardenAD/SecureAD#92]
The WMI filter: 

- Inputs/GroupPolicies/WmiFilters/Windows-x64-NoDC.mof does not work on Windows Server 2022. 
 
Row 13 needs to be modified: 
              Query = "SELECT * FROM Win32_operatingsystem WHERE OSArchitecture="64-bit" AND NOT ProductType="2"";
              to
              Query = "SELECT * FROM Win32_operatingsystem WHERE OSArchitecture **LIKE "%64%**" AND NOT ProductType="2"";

**Comment by LoicVeirman** [comment]
Nice one ;) Update to come in 2.9.8

**Comment by LoicVeirman** [comment]
I have perform some test on 2k22 servers, the filters is working as is (osarchitecture="64-bit"). So, based on your input, I'll guess this is a random glitch that occurs - As your proposed solution is also working in my test environment, I will change the filter this way.

Update in release 2.9.8.

**Comment by gherubel** [comment]
When i request the WMI : Get-WmiObject -Query "SELECT OSArchitecture FROM Win32_OperatingSystem" in powershell, the result is without the "-"
![image](https://github.com/LoicVeirman/HardenAD/assets/167763916/b17558b4-aafe-49de-ba6b-1244a8027f46)
