### ISSUE TITLE
L-S_LocalAdmins_%ComputerName% group creation

### ISSUE THREAD

**Issue by livarkhal** [HardenAD/SecureAD#94]
Hi,

We found a bug in the creation of L-S-LocalAdmins_%ComputerName%.

The group is created like L-S-LocalAdmins_%ComputerName%, but in the GPO HAD-LocalAdmins-T2 for exemple, it try to set the group L-S_LocalAdmins_%ComputerName% (with "_" after L-S instead of the "-").
So, the group for the computer is not added to the admin local group on the computer.

I think it's better to change the XML with the right nomenclature (like the group L-S-T2_LocalAdmins_Workstations) but i don't know if the Prefix-domLOC translation is used in another script.

Thanks :D

**Comment by LoicVeirman** [comment]
Thanks livarkhal. I'll get a check upon this, I'll also noticed this pb a few months ago but though I had fixed it - missed one point it seems ;)

**Comment by livarkhal** [comment]
Hi :)

After some research, ti seems that Prefix-domLOC is only used for localadmin scripts.
So we decided to change this directly in the tasksequence.xml :D 

Thanks

**Comment by LoicVeirman** [comment]
Hello,

I have release a new version that fix definitively this bug. If you download the zip fix (2024-07-24), you'll get 2 script in 'Tools / Scripts Fix' that will : 
> Replace the *guest user* per *Guests group* in LoginRestriction GPO (Network Access)
> Replace the content of translation.xml in LocalAdmins GPO (now use proper variable).

If you have the issue in place (means : not the right values in GPO), simply remove the existing ones and rerun the script (sequences *Prepare GPO files before GPO import* and *Import new GPO or update existing ones*)

Enjoy ;)
