### ISSUE TITLE
GPO HAD-LocalAdmins: bad group name during import

### ISSUE THREAD

**Issue by LoicVeirman** [HardenAD/SecureAD#99]
**Describe the bug**
The version 2.9.8 generate HAD-LocalAdmins-XXX GPOs with a wrong name translation in the preferences section.

**To Reproduce**
1. Go to 'gpmc.msc'
2. Click on 'HAD-LocalAdmins-T1'
3. Navigate to the 'Setings' panel 
4. check the local group administrators: it must contains %domain%\L-S-T1_LocalAdmins_Servers 

**Expected behavior**
%domain% should ave been replaced with your domain netbios name.

**Screenshots**
<img width="1376" alt="image" src="https://github.com/LoicVeirman/HardenAD/assets/85032445/b9bae5bd-1cd1-4a0a-853f-091c22bafa57">

**Quick fix**
Edit your *tasksSequence_hardenAD.xml* file and add the following line in the translation section:

``<wellKnownID objectClass="text" translateFrom="%domain%" translateTo="HARDEN" />``

(Do not forget to replace HARDEN with your domain netbios name). 

Once done, delete the GPOs HAD-LocalAdmins-XXX and reimport the GPO through the script.... Or edit them manually ;)

**Permanent fix**
A 2.9.8b QuickFix Edition will be release.

**Comment by LoicVeirman** [comment]
Pb fixed.

**Comment by livarkhal** [comment]
Hi,

I have a question about this, why don't modify the script to use the <wellKnownID objectClass="text" translateFrom="%NetBios%" translateTo="HARDEN" /> instead of add another line where we have to think to change it in addition to change the others?

Thanks :)
